# Version of the configuration file
version: 3.0.0
# Icarus theme variant, can be "default" or "cyberpunk"
variant: default
# Path or URL to the website's logo
logo: https://pic.imgdb.cn/item/5e3d0e712fb38b8c3c048512.jpg
# Page metadata configurations
head:
    # URL or path to the website's icon
    favicon: /img/favicon.png
    # Open Graph metadata
    # https://hexo.io/docs/helpers.html#open-graph
    open_graph:
        # Page title (og:title) (optional)
        # You should leave this blank for most of the time
        title: 
        # Page type (og:type) (optional)
        # You should leave this blank for most of the time
        type: blog
        # Page URL (og:url) (optional)
        # You should leave this blank for most of the time
        url: 
        # Page cover (og:image) (optional) Default to the Open Graph image or thumbnail of the page
        # You should leave this blank for most of the time
        image: 
        # Site name (og:site_name) (optional)
        # You should leave this blank for most of the time
        site_name: 
        # Page author (article:author) (optional)
        # You should leave this blank for most of the time
        author: 
        # Page description (og:description) (optional)
        # You should leave this blank for most of the time
        description: 
        # Twitter card type (twitter:card)
        twitter_card: 
        # Twitter ID (twitter:creator)
        twitter_id: 
        # Twitter ID (twitter:creator)
        twitter_site: 
        # Google+ profile link (deprecated)
        google_plus: 
        # Facebook admin ID
        fb_admins: 
        # Facebook App ID
        fb_app_id: 
    # Structured data of the page
    # https://developers.google.com/search/docs/guides/intro-structured-data
    structured_data:
        # Page title (optional)
        # You should leave this blank for most of the time
        title: 
        # Page description (optional)
        # You should leave this blank for most of the time
        description: 
        # Page URL (optional)
        # You should leave this blank for most of the time
        url: 
        # Page author (article:author) (optional)
        # You should leave this blank for most of the time
        author: 
        # Page images (optional) Default to the Open Graph image or thumbnail of the page
        # You should leave this blank for most of the time
        image: 
    # Additional HTML meta tags in an array
    meta:
        # Meta tag specified in <attribute>=<value> style
        # E.g., name=theme-color;content=#123456 => <meta name="theme-color" content="#123456">
        - ''
    # URL or path to the website's RSS atom.xml
    rss: 
# Page top navigation bar configurations
navbar:
    # Naviagtion menu items
    menu:
        主页: /
        归档: /archives
        分类: /categories
        广场: /categories/广场
        链接: /links
        关于: /about
    # Links to be shown on the right of the navigation bar
    #links:
        #Download on GitHub:
            #icon: fab fa-github
            #url: 'https://github.com/ppoffice/hexo-theme-icarus'
# Page footer configurations
footer:
    # Links to be shown on the right of the footer section
    links:
        Creative Commons:
            icon: fab fa-creative-commons
            url: 'https://creativecommons.org/licenses/by-nc/4.0/legalcode'
        Attribution 4.0 International:
            icon: fab fa-creative-commons-by
            url: 'https://creativecommons.org/licenses/by/4.0/'
        Noncommercial 4.0 International:
            icon: fab fa-creative-commons-nc
            url: 'https://creativecommons.org/licenses/nc/1.0/'
# Article display settings
# Article related configurations
article:
    # Code highlight settings
    highlight:
        # Code highlight themes
        # https://github.com/highlightjs/highlight.js/tree/master/src/styles
        theme: atom-one-light
        # Show copy code button
        clipboard: true
        # Default folding status of the code blocks. Can be "", "folded", "unfolded"
        fold: unfolded
    # Whether to show thumbnail image for every article
    thumbnail: true
    # Whether to show estimated article reading time
    readtime: true
# Search plugin configurations
# https://ppoffice.github.io/hexo-theme-icarus/categories/Plugins/Search/
search:
    type: insight
# Comment plugin configurations
# https://ppoffice.github.io/hexo-theme-icarus/categories/Plugins/Comment/
comment:
    type: valine
    app_id: vT1h18rwSYXRzHvHY4oYj9Rj-gzGzoHsz        # (required) LeanCloud application id
    app_key: cR290DhR9b7yrogNs9p4KcAk       # (required) LeanCloud application key
    notify: false           # (optional) receive email notification
    verify: true           # (optional) show verification code
    placeholder: 呐呐，欢迎评论!   # (optional) comment box placeholder text
# Donate plugin configurations
# https://blog.zhangruipeng.me/hexo-theme-icarus/categories/Plugins/Donation/
#donates:
    # Alipay donate button configurations
    #-
        #type: alipay
        # Alipay qrcode image URL
        #qrcode: ''
    # "Buy me a coffee" donate button configurations
    #-
        #type: buymeacoffee
        # URL to the "Buy me a coffee" page
        #url: ''
    # Patreon donate button configurations
    #-
        #type: patreon
        # URL to the Patreon page
        #url: ''
    # Paypal donate button configurations
    #-
        #type: paypal
        # Paypal business ID or email address
        #business: ''
        # Currency code
        #currency_code: USD
    # Wechat donate button configurations
    #-
        #type: wechat
        # Wechat qrcode image URL
        #qrcode: ''
# Share plugin configurations
# https://ppoffice.github.io/hexo-theme-icarus/categories/Plugins/Share/
#share:
    # Share plugin name
    #type: sharejs
# Sidebar configurations.
# Please be noted that a sidebar is only visible when it has at least one widget
sidebar:
    # Left sidebar configurations
    left:
        # Whether the sidebar sticks to the top when page scrolls
        sticky: false
    # Right sidebar configurations
    right:
        # Whether the sidebar sticks to the top when page scrolls
        sticky: false
# Sidebar widget configurations
# http://ppoffice.github.io/hexo-theme-icarus/categories/Widgets/
widgets:
    # Profile widget configurations
    -
        # Where should the widget be placed, left sidebar or right sidebar
        position: left
        type: profile
        # Author name
        author: nek0ri
        # Author title
        author_title: 我们能做得更好
        # Author's current location
        location: Deutschland
        # URL or path to the avatar image
        avatar: https://pic.imgdb.cn/item/5e8ea4a6504f4bcb04fba03c.jpg
        # Whether show the rounded avatar image
        avatar_rounded: true
        # Email address for the Gravatar
        gravatar: 
        # URL or path for the follow button
        follow_link: 'https://www.zhihu.com/people/mattlee'
        # Links to be shown on the bottom of the profile widget
        social_links:
            Telegram:
                icon: fab fa-telegram-plane
                url: 'https://t.me/nek0ri'
            #Facebook:
                #icon: fab fa-facebook
                #url: 'https://facebook.com'
            Twitter:
                icon: fab fa-twitter
                url: 'https://twitter.com/mattlee999'
            #Dribbble:
                #icon: fab fa-dribbble
                #url: 'https://dribbble.com'
            Instagram:
                icon: fab fa-instagram
                url: 'https://instagram.com/mizai2010'
            Github:
                icon: fab fa-github
                url: 'https://github.com/nek0ri'
            RSS:
                icon: fas fa-rss
                url: /atom.xml
    # Table of contents widget configurations
    -
        # Where should the widget be placed, left sidebar or right sidebar
        position: left
        type: toc
    # Recommendation links widget configurations
    #-
        # Where should the widget be placed, left sidebar or right sidebar
        #position: left
        #type: links
        # Names and URLs of the sites
        #links:
            #Hexo: 'https://hexo.io'
            #Bulma: 'https://bulma.io'
    # Categories widget configurations
    -
        # Where should the widget be placed, left sidebar or right sidebar
        position: left
        type: categories
    # Recent posts widget configurations
    -
        # Where should the widget be placed, left sidebar or right sidebar
        position: right
        type: recent_posts
    # Archives widget configurations
    -
        # Where should the widget be placed, left sidebar or right sidebar
        position: right
        type: archives
    # Tags widget configurations
    -
        # Where should the widget be placed, left sidebar or right sidebar
        position: left
        type: tags
    # Google FeedBurner email subscription widget configurations
    -
        # Where should the widget be placed, left sidebar or right sidebar
        position: left
        type: subscribe_email
        # Hint text under the email input
        description: 
        # Feedburner ID
        feedburner_id: 'nek0ri/lrIL'
    # Google AdSense unit configurations
    #-
        # Where should the widget be placed, left sidebar or right sidebar
        #position: right
        #type: adsense
        # AdSense client ID
        #client_id: 'ca-pub-6623090912480321'
        # AdSense AD unit ID
        #slot_id: ''
# Plugin configurations
plugins:
    # Enable page startup animations
    animejs: true
    # Show the "back to top" button
    back_to_top: true
    # Baidu Analytics plugin settings
    # https://tongji.baidu.com
    baidu_analytics:
        # Baidu Analytics tracking ID
        tracking_id: 
    # BuSuanZi site/page view counter
    # https://busuanzi.ibruce.info
    busuanzi: false
    # CNZZ statistics
    # https://www.umeng.com/web
    cnzz:
        # CNZZ tracker id
        id: 
        # CNZZ website id
        web_id: 
    # Enable the lightGallery and Justified Gallery plugins
    # https://ppoffice.github.io/hexo-theme-icarus/Plugins/General/gallery-plugin/
    gallery: true
    # Google Analytics plugin settings
    # https://analytics.google.com
    google_analytics:
        # Google Analytics tracking ID
        tracking_id: 
    # Hotjar user feedback plugin
    # https://www.hotjar.com/
    hotjar:
        # Hotjar site id
        site_id: 
    # Enable the KaTeX math typesetting supprot
    # https://katex.org/
    katex: false
    # Enable the MathJax math typesetting support
    # https://www.mathjax.org/
    mathjax: true
    # Enable the Outdated Browser plugin
    # http://outdatedbrowser.com/
    outdated_browser: true
    # Show a progress bar at top of the page on page loading
    progressbar: true
# CDN provider settings
# https://ppoffice.github.io/hexo-theme-icarus/Configuration/Theme/speed-up-your-site-with-custom-cdn/
providers:
    # Name or URL template of the JavaScript and/or stylesheet CDN provider
    cdn: jsdelivr
    # Name or URL template of the webfont CDN provider
    fontcdn: 'https://fonts.lug.ustc.edu.cn/${type}?family=${fontname}'
    # Name or URL of the fontawesome icon font CDN provider
    iconcdn: 'https://cdn.bootcss.com/font-awesome/5.11.2/css/all.css'
